import type { StringTable } from '../i18n'

// Amharic below is machine-made. It needs a native speaker check before anyone relies on it.
export const strings: StringTable = {
  en: {
    'simulation.place.aricha': 'Aricha washing station',
    'simulation.place.arichaWater': 'Aricha water point',
    'simulation.place.market': 'market',
    'simulation.place.clinic': 'animal health post',
    'simulation.place.homeDomorso': 'Domorso homestead',
    'simulation.place.homeKonga': 'Konga homestead',
    'simulation.place.homeHaru': 'Haru road homestead',
    'simulation.place.homeBenko': 'Benko homestead',
    'simulation.place.homeAdido': 'Adido road homestead',
    'simulation.household.domorso': 'Domorso household',
    'simulation.household.konga': 'Konga household',
    'simulation.household.haru': 'Haru road household',
    'simulation.household.benko': 'Benko household',
    'simulation.household.adido': 'Adido road household',
    'simulation.cooperative': 'Aricha cooperative',
    'simulation.log.quiet': '{name} was quieter than usual: less eating and walking.',
    'simulation.log.moreLying': '{name} lay down more than usual.',
    'simulation.log.upDowns': '{name} got up and lay down again and again in the evening.',
    'simulation.log.rolling': '{name} rolled more than once within half an hour.',
    'simulation.log.noWater': '{name} worked all morning without a water stop.',
    'simulation.log.heat': 'Afternoon heat on top of the work.',
    'simulation.log.longWork': '{name} was ridden for over 4 hours without water.',
    'simulation.log.fall': 'Possible fall: a hard impact, a fast turn, then lying.',
  },
  am: {
    'simulation.place.aricha': 'የአሪቻ ቡና ማጠቢያ',
    'simulation.place.arichaWater': 'የአሪቻ ውሃ መጠጫ',
    'simulation.place.market': 'ገበያ',
    'simulation.place.clinic': 'የእንስሳት ጤና ኬላ',
    'simulation.place.homeDomorso': 'የዶሞርሶ መኖሪያ',
    'simulation.place.homeKonga': 'የኮንጋ መኖሪያ',
    'simulation.place.homeHaru': 'የሀሩ መንገድ መኖሪያ',
    'simulation.place.homeBenko': 'የቤንኮ መኖሪያ',
    'simulation.place.homeAdido': 'የአዲዶ መንገድ መኖሪያ',
    'simulation.household.domorso': 'የዶሞርሶ ቤተሰብ',
    'simulation.household.konga': 'የኮንጋ ቤተሰብ',
    'simulation.household.haru': 'የሀሩ መንገድ ቤተሰብ',
    'simulation.household.benko': 'የቤንኮ ቤተሰብ',
    'simulation.household.adido': 'የአዲዶ መንገድ ቤተሰብ',
    'simulation.cooperative': 'የአሪቻ ማህበር',
    'simulation.log.quiet': '{name} ከወትሮው ፀጥ ብሏል፤ መብላትና መራመድ ቀንሷል።',
    'simulation.log.moreLying': '{name} ከወትሮው በላይ ተኝቷል።',
    'simulation.log.upDowns': '{name} ማታ ደጋግሞ ተኝቶ ተነስቷል።',
    'simulation.log.rolling': '{name} በግማሽ ሰዓት ውስጥ ከአንድ ጊዜ በላይ ተንከባሏል።',
    'simulation.log.noWater': '{name} ጠዋቱን ሙሉ ውሃ ሳይጠጣ ሰርቷል።',
    'simulation.log.heat': 'ከስራው በተጨማሪ የከሰዓት ሙቀት።',
    'simulation.log.longWork': '{name} ከ4 ሰዓት በላይ ውሃ ሳይጠጣ ተጋልቧል።',
    'simulation.log.fall': 'ምናልባት ወድቋል፤ ጠንካራ ግጭት፣ ፈጣን መዞር፣ ከዚያ መተኛት።',
  },
}
