import type { StringTable } from '../i18n'

// The case file of one animal. Short labels stay in sentence case here; CSS sets mono caps.
// Amharic falls back to English for now.
export const strings: StringTable = {
  en: {
    'animal.title': 'Case file',
    'animal.unknown.title': 'No animal with this tag in the herd.',
    'animal.unknown.body': 'The link may be old, or the tag moved to another cooperative.',
    'animal.unknown.back': 'Back to the herd',

    'animal.updated': 'Updated {minutes} min ago',
    'animal.updatedNow': 'Updated less than 1 min ago',
    'animal.details': '{species}, {sex}, {age} years, {weight} kg',
    'animal.sex.female': 'female',
    'animal.sex.male': 'male',
    'animal.work.pack': 'Pack work',
    'animal.work.cart': 'Cart work',
    'animal.work.riding': 'Riding',
    'animal.tag': 'Tag {tag}',
    'animal.pose': 'Now: {pose}',
    'animal.reasons': 'What the tag saw',
    'animal.showOnMap': 'Show on map',
    'animal.tagScreen': 'How the tag decides',

    'animal.next.title': 'What to do next',
    'animal.next.lead': "Suggested from {name}'s data. You know {name}. You make the call.",
    'animal.whatIf.title': 'Water plans',
    'animal.whatIf.lead':
      "What the water model expects under each plan. The deficit is water lost since the last full drink, as a share of {name}'s body weight.",
    'animal.whatIf.plan': 'Plan',
    'animal.whatIf.at': 'At {time}',
    'animal.whatIf.passes': 'Passes 5%',
    'animal.whatIf.never': 'Not before {time}',
    'animal.whatIf.pct': '{pct}%',
    'animal.whatIf.caption': 'Water deficit, % of body weight',
    'animal.whatIf.note': 'The water model is an estimate from work, weather and water stops. It cannot see how {name} looks. Check the gums and skin yourself.',

    'animal.today.title': 'Today',
    'animal.today.lead': "Midnight to {time}, against {name}'s normal for the same hours on the last {days} days.",
    'animal.today.leadLearning': "The tag is still learning {name}'s normal. Today's numbers are shown without a normal.",
    'animal.card.activity': 'Activity',
    'animal.card.lying': 'Lying',
    'animal.card.eating': 'Eating',
    'animal.card.workload': 'Workload',
    'animal.card.distance': 'Distance',
    'animal.card.climb': 'Climb',
    'animal.card.waterDebt': 'Water deficit',
    'animal.unit.activity': '%',
    'animal.unit.lying': 'min',
    'animal.unit.eating': 'min',
    'animal.unit.workload': 'points',
    'animal.unit.distance': 'km',
    'animal.unit.climb': 'm',
    'animal.unit.waterDebt': '%',
    'animal.foot.activity': 'Share of free time spent walking or eating.',
    'animal.foot.workload': '0 to 100. 8 hours of work is 100.',
    'animal.foot.lyingNow': 'Lying now for about {minutes} min.',
    'animal.foot.waterDebt': 'Of body weight. An estimate from the water model.',

    'animal.trends.title': 'Trends',
    'animal.trends.range': 'Time range',
    'animal.trends.group': 'Signals',
    'animal.trends.behaviour': 'Behaviour',
    'animal.trends.work': 'Work and water',
    'animal.range.today': 'Today',
    'animal.range.d7': '7 days',
    'animal.range.d30': '30 days',
    'animal.range.m6': '6 months',
    'animal.trends.learning': "Trends start when the tag has learned {name}'s normal. Day {day} of {of}.",
    'animal.trends.noData': 'No data from the tag for this range.',
    'animal.chart.title': '{signal}, {range}',
    'animal.chart.descToday':
      "Hatched band: {name}'s normal for each hour. Line: measured. Dashed line and light hatching: expected for the rest of today.",
    'animal.chart.descWeek':
      "One point per day, at the end of the day. Hatched band: {name}'s normal from the 14 days before. Dashed line: today's expected total.",
    'animal.chart.desc':
      "One point per day, at the end of the day. Hatched band: {name}'s normal from the 14 days before.",
    'animal.chartUnit.today.activity': '% active',
    'animal.chartUnit.today.lying': 'min per hour',
    'animal.chartUnit.today.eating': 'min per hour',
    'animal.chartUnit.today.workload': 'points per hour',
    'animal.chartUnit.today.distance': 'km per hour',
    'animal.chartUnit.today.waterDebt': '% of body weight',
    'animal.chartUnit.day.activity': '% active',
    'animal.chartUnit.day.lying': 'min per day',
    'animal.chartUnit.day.eating': 'min per day',
    'animal.chartUnit.day.workload': 'points per day',
    'animal.chartUnit.day.distance': 'km per day',

    'animal.changes.title': 'Detected changes',
    'animal.changes.lead':
      "Each entry is a change from {name}'s own normal. The tag cannot say why. A person looks and records what they found.",
    'animal.changes.learning': "The tag records changes once it has learned {name}'s normal.",
    'animal.changes.none': "No changes from {name}'s normal so far.",
    'animal.changes.ask': 'What did you find when you looked?',
    'animal.changes.askOld': 'No answer recorded.',
    'animal.changes.answer': 'Record what you found',
    'animal.changes.saved': 'Saved on this phone.',
    'animal.changes.fromOwner': 'Recorded by the owner.',
    'animal.changes.older': 'Show {count} older entries',
    'animal.changes.feedbackGroup': 'Answer for the change on {date}',

    'animal.cannotSee.title': 'What the tag cannot see',
    'animal.cannotSee.body':
      'The tag measures movement, lying and position. It cannot see droppings, gums, sweating or heart rate. Look at {name} yourself.',
    'animal.cannotSee.change':
      "The tag detects change from {name}'s own normal. It does not detect colic or any other illness. A normal learned while {name} was unwell treats unwell as normal.",
  },
}
